### ISSUE TITLE
Request for Assistance with Compiling Elden Ring Project

### ISSUE THREAD

**Issue by rohybnol** [ItsSenko/EldenRing-PvP-Helper#4]
Hello,

Could you please provide guidance on the simplest method to compile on my own? I attempted a basic fork, but it appears that erdtools is outdated. I tried using the dlc branch, but it seems not everything has been correctly uploaded or updated on your GitHub. I managed to run it, but it failed on a hook at address 0xD39410:
```public static IntPtr GetEquipGoodsEntryParamPtr(int id)
        {
            var hook = ExtensionsCore.GetMainHook();

            PHPointer pointer = hook.CreateBasePointer(hook.Process.MainModule.BaseAddress + 0xD39410);
            IntPtr entryPtr = hook.GetPrefferedIntPtr(16);
            PHPointer ptr = hook.CreateBasePointer(entryPtr);

            string asmStr = Helpers.GetEmbededResource("Resources.Assembly.GetEquipParamGoodsEntry.asm");
            string formattedStr = string.Format(asmStr, entryPtr, id, pointer.Resolve());

            hook.AsmExecute(formattedStr);

            return ptr.ReadIntPtr(0x8);
        }
```

The standalone executable works fine, but I would like to compile it myself to experiment with the Elden Ring code. 

Would the following command be sufficient?
`git clone --branch dlc --recursive https://github.com/ItsSenko/EldenRing-PvP-Helper.git`

I got it to the point where it just crashes after trying to attach. I tried everything I know, but it seems the version on the GitHub source does not match the current released executable version.

Best regards

**Comment by ItsSenko** [comment]
Heyo!

I have updated the dlc branch to be the same as the latest released version. That should work no issue. The only requirement right now for anyone attempting to compile is that they will need to add two functions in the file `PropertyHook/PHPointer/PHPointer.cs`

```cs
public byte ReadByte(long offset)
{
    return Kernel32.ReadByte(Hook.Handle, (IntPtr)(Resolve().ToInt64() + offset));
}

public bool WriteByte(long offset, byte value)
{
    return Kernel32.WriteByte(Hook.Handle, (IntPtr)(Resolve().ToInt64() + offset), value);
}
```

Other than that, all should be good! C:

**Comment by rohybnol** [comment]
I attempted to fork the latest version of your repository, but encountered a crash at the following code segment:
```
      public static IntPtr GetEquipGoodsEntryParamPtr(int id)
        {
            var hook = ExtensionsCore.GetMainHook();

            PHPointer pointer = hook.CreateBasePointer(hook.Process.MainModule.BaseAddress + 0xD39410);
            IntPtr entryPtr = hook.GetPrefferedIntPtr(16);
            PHPointer ptr = hook.CreateBasePointer(entryPtr);

            string asmStr = Helpers.GetEmbededResource("Resources.Assembly.GetEquipParamGoodsEntry.asm");
            string formattedStr = string.Format(asmStr, entryPtr, id, pointer.Resolve());

            hook.AsmExecute(formattedStr);

            return ptr.ReadIntPtr(0x8);
        }
```

The crash occurs specifically at this line:
`PHPointer pointer = hook.CreateBasePointer(hook.Process.MainModule.BaseAddress + 0xD39410);`

When I comment out the following block of code:
```
 public static void InitializeSeamlessItems()
        {
            //var hook = ExtensionsCore.GetMainHook();

            //if (!hook.Setup)
              //return;


            //for(int i = 0; i < Enum.GetValues(typeof(SeamlessItems)).Length; i++)
            //{
            //    var array = Enum.GetValues(typeof(SeamlessItems)).Cast<SeamlessItems>().ToArray();

            //    IntPtr paramPtr = GetEquipGoodsEntryParamPtr((int)array[i]);
            //    long dataOffset = GetParamDataOffset(paramPtr, hook.EquipParamGoods);

            //    hook.EquipParamGoods.Rows.Add(new(hook.EquipParamGoods, array[i].ToString(), (int)array[i], dataOffset));
            //}
            SeamlessItemsInitialized = true;
        }
```

the application runs without crashing, but only partial functionality is available (e.g., item spawning does not work).

I am uncertain of the root cause of this issue, but it appears there are missing or outdated components compared to the original standalone version you uploaded.

Any guidance on resolving this would be appreciated.

**Comment by ItsSenko** [comment]
This was fixed by making use of the proper cloning command.

```
git clone -b dlc --recurse-submodules -j8 https://github.com/ItsSenko/EldenRing-PvP-Helper
```
